"""add count column

Revision ID: ee0de77b4ea5
Revises: 9e299bc7d907
Create Date: 2026-01-14 08:10:42.564291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0de77b4ea5'
down_revision: Union[str, Sequence[str], None] = '9e299bc7d907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('index_unique_order_product'), 'order_product_association', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('index_unique_order_product'), 'order_product_association', ['order_id', 'product_id'])
    # ### end Alembic commands ###
